
import java.util.Stack;
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tadeo
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
            Stack<Nodo>  pOperandos = new Stack< Nodo>();
            Stack< String> pOperadores = new Stack< String>();
            final String blanco;
            // Cadena de espacios en blanco
            final String operadores;
            // Cadena con operadores para expresiones
    
    
    public Aplicacion() {
        initComponents();
        blanco = " \t"; 
        operadores =")+-*/%^(";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

                private void guardarSubArbol() 
                {
                Nodo op2 = (Nodo) pOperandos.pop();
                Nodo op1 = (Nodo) pOperandos.pop();
                pOperandos.push(new Nodo( pOperadores.pop(), op1 , op2));
                }
    
                private Nodo raiz;
                
                
                public void Inorder(Nodo n)
                {
                    if(n!=null){
                    derivada.append(n.getData()  + "");
                    Inorder(n.getRight());
                    Inorder(n.getLeft());
                   
                    
                    }
                }
                
    //construir nodo root
        public  Nodo construct(String cadena)
        {
           StringTokenizer tokenizer; //Permite dividir la cadena ingresada
           String token; //Para almacenar el token a analizar
           tokenizer = new StringTokenizer (cadena , blanco + operadores, true);
             //Divide la expresión ingresada y las separa, evaluando los delimitadores como tokens
             while (tokenizer.hasMoreTokens ()) 
             { //Mientra existan más tokens disponibles
                 token = tokenizer.nextToken(); //Devuelve el siguiente token del objeto StringTokenizer.
                 if (blanco.indexOf (token) >= 0)
                     ; // Si el token es un espacio en blanco, se ignora
                 else if (operadores.indexOf (token) < 0)
                 {
                     
                     // Si el token es un operando, lo guarda como nodo del arbol
                    Nodo a;
                    pOperandos.push (new Nodo (token));
                 } 
                 else 
                     if(token.equals(")"))
                     {
                         while(!pOperadores.empty() && !pOperadores.peek().equals("("))
                             guardarSubArbol();
                      pOperadores.pop();
                         
                     } 
                     else
                     {
                          if(!token.equals("(") && !pOperadores.empty())
                          {
                            
                           String op = (String) pOperadores.peek();
                           while(op.equals("(") && !pOperadores.empty() && operadores.indexOf(op)>= operadores.indexOf(token))
                           {
                               guardarSubArbol();
                               if(!pOperadores.empty())
                                   op = (String) pOperadores.peek();
                           }
                          
                          }
                          pOperadores.push(token);
                     }
                         
             }
             raiz = (Nodo) pOperandos.peek();
              while(!pOperadores.empty())
              {
                  if(pOperadores.peek().equals("("))
                      pOperadores.pop();
                  else
                  {
                      guardarSubArbol();
                      raiz = (Nodo) pOperandos.peek();


                  }
                  
              }
             
             
             
             return raiz;
        }
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        func = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        suma = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        division = new javax.swing.JButton();
        variableX = new javax.swing.JButton();
        Multiplicacion = new javax.swing.JButton();
        cosx = new javax.swing.JButton();
        numero9 = new javax.swing.JButton();
        numero1 = new javax.swing.JButton();
        numero4 = new javax.swing.JButton();
        numero2 = new javax.swing.JButton();
        numero7 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        sinx = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        numero5 = new javax.swing.JButton();
        numero3 = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        ParentesisDerecho = new javax.swing.JButton();
        parentesisDerecho = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        derivada = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        func.setEditable(false);

        jLabel1.setText("Función");

        jLabel2.setText("Derivada de la Función");

        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        potencia.setText("^");
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });

        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        variableX.setText("X");
        variableX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableXActionPerformed(evt);
            }
        });

        Multiplicacion.setText("*");
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });

        cosx.setText("cos(X)");
        cosx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosxActionPerformed(evt);
            }
        });

        numero9.setText("9");
        numero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero9ActionPerformed(evt);
            }
        });

        numero1.setText("1");
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        numero4.setText("4");
        numero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero4ActionPerformed(evt);
            }
        });

        numero2.setText("2");
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });

        numero7.setText("7");
        numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero7ActionPerformed(evt);
            }
        });

        numero8.setText("8");
        numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero8ActionPerformed(evt);
            }
        });

        sinx.setText("sin(X)");
        sinx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinxActionPerformed(evt);
            }
        });

        numero6.setText("6");
        numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero6ActionPerformed(evt);
            }
        });

        numero5.setText("5");
        numero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero5ActionPerformed(evt);
            }
        });

        numero3.setText("3");
        numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero3ActionPerformed(evt);
            }
        });

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        ParentesisDerecho.setText("(");
        ParentesisDerecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParentesisDerechoActionPerformed(evt);
            }
        });

        parentesisDerecho.setText(")");
        parentesisDerecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisDerechoActionPerformed(evt);
            }
        });

        jButton21.setText("Borrar Todo");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton1.setText("Derivada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        derivada.setColumns(20);
        derivada.setRows(5);
        jScrollPane1.setViewportView(derivada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(func, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sinx)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cosx)
                                    .addGap(18, 18, 18)
                                    .addComponent(variableX))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numero7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(numero8)
                                    .addGap(18, 18, 18)
                                    .addComponent(numero9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numero2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numero4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numero6)
                                    .addComponent(numero3))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(potencia)
                                    .addComponent(division)
                                    .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton21)
                                    .addComponent(Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parentesisDerecho)
                                    .addComponent(ParentesisDerecho)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Borrar, Multiplicacion, ParentesisDerecho, cosx, division, jButton21, menos, numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, parentesisDerecho, potencia, sinx, suma, variableX});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {func, jScrollPane1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero2)
                            .addComponent(numero3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero4)
                            .addComponent(numero5)
                            .addComponent(numero6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero7)
                            .addComponent(numero8)
                            .addComponent(numero9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(variableX)
                            .addComponent(cosx)
                            .addComponent(sinx))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(division)
                                .addGap(18, 18, 18)
                                .addComponent(potencia))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ParentesisDerecho)
                                    .addComponent(jButton21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(parentesisDerecho)
                                    .addComponent(Multiplicacion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(suma)
                                    .addComponent(menos))))
                        .addGap(46, 46, 46))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Borrar, Multiplicacion, ParentesisDerecho, cosx, division, jButton1, jButton21, menos, numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, parentesisDerecho, potencia, sinx, suma, variableX});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {func, jScrollPane1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "-";
        func.setText(x);
    }//GEN-LAST:event_menosActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "*";
        func.setText(x);
    }//GEN-LAST:event_MultiplicacionActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "^";
        func.setText(x);
    }//GEN-LAST:event_potenciaActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "1";
        func.setText(x);
        
    }//GEN-LAST:event_numero1ActionPerformed

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "2";
        func.setText(x);
    }//GEN-LAST:event_numero2ActionPerformed

    private void numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "3";
        func.setText(x);
    }//GEN-LAST:event_numero3ActionPerformed

    private void numero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero4ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "4";
        func.setText(x);
    }//GEN-LAST:event_numero4ActionPerformed

    private void numero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero5ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "5";
        func.setText(x);
    }//GEN-LAST:event_numero5ActionPerformed

    private void numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero6ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "6";
        func.setText(x);
    }//GEN-LAST:event_numero6ActionPerformed

    private void numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero7ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "7";
        func.setText(x);
    }//GEN-LAST:event_numero7ActionPerformed

    private void numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero8ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "8";
        func.setText(x);
    }//GEN-LAST:event_numero8ActionPerformed

    private void numero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero9ActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "9";
        func.setText(x);
    }//GEN-LAST:event_numero9ActionPerformed

    private void variableXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableXActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "x";
        func.setText(x);
    }//GEN-LAST:event_variableXActionPerformed

    private void cosxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosxActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "cos(x)";
        func.setText(x);
    }//GEN-LAST:event_cosxActionPerformed

    private void sinxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinxActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "sin(x)";
        func.setText(x);
    }//GEN-LAST:event_sinxActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "+";
        func.setText(x);
    }//GEN-LAST:event_sumaActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        String x =  "";
        func.setText(x);
        derivada.setText(x);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "/";
        func.setText(x);
    }//GEN-LAST:event_divisionActionPerformed

    private void parentesisDerechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisDerechoActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + ")";
        func.setText(x);
    }//GEN-LAST:event_parentesisDerechoActionPerformed

    private void ParentesisDerechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParentesisDerechoActionPerformed
        // TODO add your handling code here:
        String x = func.getText() + "(";
        func.setText(x);
    }//GEN-LAST:event_ParentesisDerechoActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        String x = func.getText();
        if(x.length()!=0)
        {
        int i =x.length()-1;
        x=x.substring(0,i);
        func.setText(x);
        }
        
    }//GEN-LAST:event_BorrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Nodo raiz = construct(func.getText());
        Inorder(raiz);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton ParentesisDerecho;
    private javax.swing.JButton cosx;
    private javax.swing.JTextArea derivada;
    private javax.swing.JButton division;
    private javax.swing.JTextField func;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menos;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero2;
    private javax.swing.JButton numero3;
    private javax.swing.JButton numero4;
    private javax.swing.JButton numero5;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero7;
    private javax.swing.JButton numero8;
    private javax.swing.JButton numero9;
    private javax.swing.JButton parentesisDerecho;
    private javax.swing.JButton potencia;
    private javax.swing.JButton sinx;
    private javax.swing.JButton suma;
    private javax.swing.JButton variableX;
    // End of variables declaration//GEN-END:variables
}
